# Generated by Django 3.0.8 on 2020-07-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0002_question_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='Question content'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=127, verbose_name='Question title'),
        ),
    ]
