# Generated by Django 3.0.8 on 2020-07-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0003_auto_20200727_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Points are given for the right answer'),
        ),
    ]
