# Generated by Django 3.0.8 on 2021-06-11 10:19

from django.db import migrations, models
import q_and_a.models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0007_image_questionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=q_and_a.models.PathAndRename('q_and_a_images/')),
        ),
    ]
