# Generated by Django 3.0.8 on 2021-06-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0008_auto_20210611_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='q_and_a.Question'),
        ),
    ]
