# Generated by Django 3.0.8 on 2021-06-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_and_a', '0009_auto_20210611_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
